#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"loadfile": "01_datasets.ipynb",
         "MantaFlowDataset": "01_datasets.ipynb",
         "getSingleSim": "01_datasets.ipynb",
         "createMantaFlowTrainTest": "01_datasets.ipynb",
         "convBlock": "02_models.ipynb",
         "convTransBlock": "02_models.ipynb",
         "Generator": "02_models.ipynb",
         "Encoder": "02_models.ipynb",
         "AE_no_P": "02_models.ipynb",
         "AE_xhat_z": "02_models.ipynb",
         "AE_xhat_zV2": "02_models.ipynb",
         "GeneratorOld": "02_models.ipynb",
         "trainEpoch": "03_train_master.ipynb",
         "validEpoch": "03_train_master.ipynb",
         "create_opt": "04_utils.ipynb",
         "create_one_cycle": "04_utils.ipynb",
         "find_lr": "04_utils.ipynb",
         "printNumModelParams": "04_utils.ipynb",
         "calcAccuracy": "04_utils.ipynb",
         "rmse": "04_utils.ipynb",
         "writeMessage": "04_utils.ipynb",
         "plotSample": "04_utils.ipynb",
         "plotSampleWpredictionByChannel": "04_utils.ipynb",
         "plotSampleWprediction": "04_utils.ipynb",
         "curl": "04_utils.ipynb",
         "jacobian": "04_utils.ipynb",
         "stream2uv": "04_utils.ipynb",
         "show": "04_utils.ipynb",
         "convertSimToImage": "04_utils.ipynb",
         "create_movie": "04_utils.ipynb"}

modules = ["datasets.py",
           "models.py",
           "train.py",
           "utils.py"]

git_url = "https://github.com/dwidemann/surrogates4sims/tree/master/"

def custom_doc_links(name): return None